### ISSUE TITLE
Set filter does not escape HTML in its virtual list items

### ISSUE THREAD

**Issue by uvtzxpm** [ag-grid/ag-grid-enterprise#110]
1. Have a column with row data such as "a > b" or "&lt;span style="background:red"&gt;oops&lt;/span&gt;".
2. Give it a filter type of set.
3. Click the column header filter, the HTML is not being escaped.

![](http://i.imgur.com/ts3tl1x.png)

Using version 8.0.1 of both ag-grid and ag-grid-enterprise.

**Comment by willhalling** [comment]
Thanks for raising @uvtzxpm 

This should be fixed in next release. You can check progress on our timeline (AG-254):

https://ag-grid.atlassian.net/browse/AG-254

**Comment by uvtzxpm** [comment]
I'm using v9.0.1 now, and the problem is still present.

AG-254 (Set filter does not escape HTML in its virtual list items) was supposedly fixed in v8.1.0, according to: https://www.ag-grid.com/ag-grid-changelog/

Can you take a look at this again? Maybe it has broken in v9.0.1?

**Comment by makinggoodsoftware** [comment]
Hi,

This should work now

Thanks
